### ISSUE TITLE
Year of Birth not getting added to Generated Password 

### ISSUE THREAD

**Issue by gautham2k3** [gautham2k3/Custom-Password-Generator#2]
Even after multiple tries Year of Birth is not coming in the Generated Password .
![Screenshot 2023-04-25 212352](https://user-images.githubusercontent.com/112716884/234333954-c33c9ac1-a1ca-4ca4-bed7-6fc53111928b.png)
![Screenshot 2023-04-25 212237](https://user-images.githubusercontent.com/112716884/234333988-5b81a0f6-039d-4498-858c-a82eba8959a4.png)

**Comment by Zwnow** [comment]
Just had a quick look at your code, but unfortunately can't find where you pass the DOB variables after assigning them. Maybe that's the issue.

**Comment by FilipeRamos92** [comment]
Hey, man!

I'd like to send a pull request with solution about this issue, but I'm not have permisson :(
Anyway. This is the solution:

`    public Password GenerateCP(int length)
    {
        final StringBuilder B=new StringBuilder("");
        int range=b.getCData().length()**-1**;
        for(int i=0;i<length;i++)
        {
            int j=(int)(Math.random()*range);
            B.append(b.getCData().charAt(j));
        }
        return new Password(B.toString());
    }`
 
You need to delete "-1" getting all of the string length. I hope help you!

**Comment by gautham2k3** [comment]
Thanks @FilipeRamos92  for the solution . can you pull request now i think i changed some settings

**Comment by FilipeRamos92** [comment]
> Thanks @FilipeRamos92 for the solution . can you pull request now i think i changed some settings

ERROR: Permission to gautham2k3/Custom-Password-Generator.git denied to FilipeRamos92.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by gautham2k3** [comment]
unable to fix that but thanks you

**Comment by FilipeRamos92** [comment]
> unable to fix that but thank you

Can you disable branch protection: Settings > Disable branch protection rules on the final page. After I push my branch, you return the settings. Please!

This is my first contributtion.
